"""
Django settings for campus_connect project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import uuid

# Every time you restart server, this changes (dev only)
DEV_SERVER_INSTANCE_ID = "dev-2"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n0v+8!&mofi4yh_&@@bk!-^vr^5u+l3%39)4jgdlmw%k_)@3#g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'core',
    'student',
    'staff',
    'notices',
    'events',
    'payments',
    'lostfound',
    'audit',
    'notifications',
    
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",

    # ✅ dev-only restart logout (safe now)
    "core.middleware.DevLogoutOnRestartMiddleware",

    # ✅ production behavior (no-cache + redirect rules)
    "core.middleware.NoCacheAndAuthRedirectMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'campus_connect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                "django.template.context_processors.media",
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "notifications.context_processors.notifications_ctx",
                
            ],
        },
    },
]

WSGI_APPLICATION = 'campus_connect.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
  'default': {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'campus_connect_db',
    'USER': 'campusconnect',
    'PASSWORD': 'Campus@123',
    'HOST': '127.0.0.1',
    'PORT': '3306',
  }
}


MIGRATION_MODULES = {
    "accounts": None,
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ---------------------------------------------------
# STATIC FILES (CSS, JS, Images like QR code)
# ---------------------------------------------------

STATIC_URL = "static/"

# This allows Django to find static files inside apps:
# payments/static/
# events/static/
# etc.
STATICFILES_DIRS = []

# ---------------------------------------------------
# MEDIA FILES (Uploaded Images - Payment Proofs)
# ---------------------------------------------------

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ---------------------------------------------------
# AUTH USER MODEL
# ---------------------------------------------------

AUTH_USER_MODEL = "accounts.User"

# ---------------------------------------------------
# DEFAULT PK
# ---------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------
# PAYMENT SETTINGS (OPTIONAL INFO ONLY)
# We DO NOT use PAYMENT_QR_URL anymore
# because we load QR via {% static %}
# ---------------------------------------------------

PAYMENT_RECEIVER_NAME = "Rohit Giri"
PAYMENT_NOTE = "Pay and upload screenshot proof."

# ============================
# EMAIL (SMTP) CONFIG
# ============================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "giri.rohit74755@gmail.com"
EMAIL_HOST_PASSWORD = "hkxzvuozumpodqum"

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Optional (recommended)
SITE_URL = "http://127.0.0.1:8000"
SITE_NAME = "Campus Connect"
DEFAULT_FROM_EMAIL = "Campus Connect <giri.rohit74755@gmail.com>"
SUPPORT_EMAIL = "support@campusconnect.com"  # optional (can be your gmail while testing)