# Generated by Django 5.2.5 on 2026-02-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='claimrequest',
            table='lostfound_claim',
        ),
        migrations.AlterModelTable(
            name='lostfounditem',
            table='lostfound_item',
        ),
    ]
